export const products = [
  {
    id: 1,
    name: "Váy Lolita Hoa Bèo",
    price: 269_000,
    originalPrice: 369_000,
    category: "Váy",
    badge: "HOT",
    // colors: ["#ff6b9e"],
    // colorNames: ["Hồng"],
    sizes: ["4kg", "5kg", "6kg", "7kg", "8kg", "9kg", "10kg", "11kg"],
    rating: 5.0,
    reviews: 124,
    images: [
      "/sp1/1.jpg",
      "/sp1/2.jpg",
      "/sp1/3.jpg",
      "/sp1/4.jpg",
      "/sp1/5.jpg",
      "/sp1/6.jpg",
      "/sp1/7.jpg",
      "/sp1/8.jpg",
      "/sp1/9.jpg",
      "/sp1/10.jpg",
      "/sp1/11.jpg",
    ],
    description:
      "Chất liệu thô mềm mát phồng váy. Mặc lên cứ gọi là ngoan xinh yêu của mẹ hết nước chấm luôn. Siêu yêu xinh cực kì dễ thương.",
    material: "Thô",
    age: "0-3 tuổi",
  },
  {
    id: 2,
    name: "Váy tơ hoa cổ tàu",
    price: 239_000,
    originalPrice: 349_000,
    category: "Váy",
    badge: "MỚI",
    // colors: ["#ff6b9e", "#ffffff"],
    // colorNames: ["Hồng", "Trắng"],
    sizes: ["4kg", "5kg", "6kg", "7kg", "8kg", "9kg", "10kg", "11kg"],
    rating: 5.0,
    reviews: 89,
    images: [
      "/sp2/1.jpg",
      "/sp2/2.jpg",
      "/sp2/3.jpg",
      "/sp2/4.jpg",
      "/sp2/5.jpg",
      "/sp2/6.jpg",
      "/sp2/7.jpg",
      "/sp2/8.jpg",
      "/sp2/9.jpg",
    ],
    description:
      "Thiết kế cổ tàu, chất mềm nhẹ. Họa tiết hoa nhí có ánh nhũ. Quá phù hợp với trung thu + Tết. May 2 lớp ( may lộn ) bọc viền.",
    material: "Tơ hoa nhí",
    age: "0-3 tuổi",
  },
  {
    id: 3,
    name: "Body dài thân Xô chấm bi",
    price: 239_000,
    originalPrice: 349_000,
    category: "Bộ đồ",
    badge: "SALE",
    // colors: ["#f472b6"],
    // colorNames: ["Hồng"],
    sizes: ["4kg", "5kg", "6kg", "7kg", "8kg", "9kg", "10kg", "11kg"],
    rating: 4.9,
    reviews: 203,
    images: [
      "/sp3/1.jpg",
      "/sp3/2.jpg",
      "/sp3/3.jpg",
      "/sp3/4.jpg",
      "/sp3/5.jpg",
    ],
    description:
      "Chất liệu Xô, Form rộng rãi thoải mái , mặc nhà hoặc ra ngoài đều rất đẹp. Phù hợp thời tiết hè và hè thu. ",
    material: "Xô",
    age: "1-5 tuổi",
  },
  {
    id: 4,
    name: "Body linen ren cách điệu",
    price: 239_000,
    originalPrice: 379_000,
    category: "Váy",
    badge: null,
    // colors: ["#ffffff"],
    // colorNames: ["Trắng"],
    sizes: ["4kg", "5kg", "6kg", "7kg", "8kg", "9kg", "10kg", "11kg"],
    rating: 4.6,
    reviews: 67,
    images: [
      "/sp4/1.jpg",
      "/sp4/2.jpg",
      "/sp4/3.jpg",
    ],
    description:
      "Body váy tiểu thư đơn giản, Chất linen mềm mỏng mát nhẹ. Họa tiết in hoa trên nền kem. Thiết kế ren ngực cách điệu đơn giản nhưng sang chảnh. Phù hợp với phong cách vintage.",
    material: "Linen",
    age: "0-7 tuổi",
  },
  {
    id: 5,
    name: "Body váy hoa nhí hồng nền kem",
    price: 239_000,
    originalPrice: 379_000,
    category: "Váy",
    badge: "BEST",
    // colors: ["#ec4899"],
    // colorNames: ["Hồng đậm"],
    sizes: ["3kg, 4kg", "5kg", "6kg", "7kg", "8kg", "9kg", "10kg", "11kg"],
    rating: 5.0,
    reviews: 312,
    images: [
      "/sp5/1.jpg",
      "/sp5/2.jpg",
      "/sp5/3.jpg",
      "/sp5/4.jpg",
      "/sp5/5.jpg",
      "/sp5/6.jpg",
      "/sp5/7.jpg",
      "/sp5/8.jpg",
    ],
    description:
      "Body váy thô lụa siêu mềm mát mịn nhẹ, Họa tiết vừa xinh vừa sang vừa Tây. Thiết kế váy xòe bồng bềnh, phần thân trên đơn giản nhưng vẫn rất tiểu thư. Phù hợp với phong cách vintage.",
    material: "Thô lụa",
    age: "2-6 tuổi",
  },
  {
    id: 6,
    name: "Body lưới hồng phối oganda",
    price: 239_000,
    originalPrice: 379_000,
    category: "Váy",
    badge: null,
    // colors: ["#f472b6"],
    // colorNames: ["Hồng"],
    sizes: ["4kg", "5kg", "6kg", "7kg", "8kg", "9kg", "10kg", "11kg"],
    rating: 4.8,
    reviews: 178,
    images: [
      "/sp6/1.jpg",
      "/sp6/2.jpg",
      "/sp6/3.jpg",
      "/sp6/4.jpg",
      "/sp6/5.jpg",
      "/sp6/6.jpg",
    ],
    description:
      "May bọc viền toàn bộ tay may lộn, mặc vào cực kì thoái mái. Mềm nhẹ ko dặm ko ngứa 1 xíu nào. Thiết kế tay lưới phối oganda bồng bềnh siêu xinh. Phù hợp với phong cách vintage.",
    material: "Lưới + Oganda",
    age: "0-5 tuổi",
  },
  {
    id: 7,
    name: "Body lưới kem hoa nổi nơ ngực",
    price: 249_000,
    originalPrice: 389_000,
    category: "Váy",
    badge: null,
    // colors: ["#ffffff"],
    // colorNames: ["Trắng"],
    sizes: ["3kg, 4kg", "5kg", "6kg", "7kg", "8kg", "9kg", "10kg", "11kg"],
    rating: 4.5,
    reviews: 94,
    images: [
      "/sp7/1.jpg",
      "/sp7/2.jpg",
      "/sp7/3.jpg",
      "/sp7/4.jpg",
      "/sp7/5.jpg",
      "/sp7/6.jpg",
      "/sp7/7.jpg",
    ],
    description:
      "Chất liệu: lưới hoa + tơ xốp, Full lót + bọc full viền. Turban dây nơ điệu đà, co giãn và ruy băng thủ công",
    material: "Lưới hoa + Tơ xốp",
    age: "0-6 tuổi",
  },
  {
    id: 8,
    name: "Váy Lolita",
    price: 279_000,
    originalPrice: 399_000,
    category: "Váy",
    badge: "HOT",
    // colors: ["#ff6b9e"],
    // colorNames: ["Hồng"],
    sizes: ["6kg", "7kg", "8kg", "9kg", "10kg", "11kg", "12kg", "13kg", "14kg"],
    rating: 4.7,
    reviews: 56,
    images: [
      "/sp8/1.jpg",
      "/sp8/2.jpg",
      "/sp8/3.jpg",
      "/sp8/4.jpg",
      "/sp8/5.jpg",
      "/sp8/6.jpg",
    ],
    description:
      "Sét váy Lolita best seller. 3 chi tiết  váy + quần chip + turrban. Vải tông màu cực yêu và sang. Chất liệu vải tơ voan hoa họa tiết hoa 6D sống động như thật.",
    material: "Tơ voan hoa 6D",
    age: "3-7 tuổi",
  },
];

export const reviews = [
  {
    id: 1,
    name: "Nguyễn Thị Hoa",
    avatar: "🌸",
    rating: 5,
    date: "15/02/2025",
    comment:
      "Sản phẩm quá đẹp, chất lượng tốt hơn mình nghĩ. Bé nhà mình thích lắm, mặc suốt ngày. Sẽ mua thêm nhiều lần nữa!",
    images: [
      "/sp1/3.jpg",
    ],
  },
  {
    id: 2,
    name: "Trần Minh Anh",
    avatar: "🦋",
    rating: 4,
    date: "10/02/2025",
    comment:
      "Giao hàng nhanh, đóng gói cẩn thận. Màu sắc đúng với hình, size vừa vặn. Chỉ mong cửa hàng có thêm nhiều mẫu hơn!",
  },
  {
    id: 3,
    name: "Lê Phương Linh",
    avatar: "🌺",
    rating: 5,
    date: "05/02/2025",
    comment:
      "Shop uy tín, sản phẩm y hình. Bé mặc vào ai cũng khen. Chất vải mềm mịn, không cứng. Rất hài lòng!",
  },
  {
    id: 4,
    name: "Phạm Thu Hằng",
    avatar: "🌈",
    rating: 5,
    date: "28/01/2025",
    comment:
      "Mua lần thứ 3 rồi vẫn không thất vọng. Shop nhiệt tình, tư vấn size chuẩn. Con tôi điệu lắm từ khi mặc đồ shop này 💕",
  },
];

export const categories = [
  "Tất cả",
  "Váy",
  "Bộ đồ",
  "Quần",
  "Áo",
  "Đồ ngủ",
  "Giày dép",
];

export const formatPrice = (p) => p.toLocaleString("vi-VN") + "đ";
